name: Deploy as snapshot

on:
  push:
    branches: [ main, 0.8.x ]

jobs:
  build:
    if: github.repository == 'figroc/r2dbc-mysql'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Temurin 8
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
          cache: maven
      - name: Deploy to repository
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: ./mvnw -B clean deploy -Psnapshot -s ./settings.xml -DskipITs -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
